# Generated by Django 4.2.4 on 2023-08-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('branch', models.CharField(choices=[('CS', 'CS'), ('EC', 'EC'), ('MECH', 'MECH')], max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudentDetails.studentdetails')),
                ('SUB1', models.IntegerField()),
                ('SUB2', models.IntegerField()),
                ('SUB3', models.IntegerField()),
            ],
        ),
    ]
