# Generated by Django 4.2.4 on 2023-08-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='id',
            new_name='admission',
        ),
    ]
