# Generated by Django 4.2.4 on 2023-08-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_number', serialize=False, to='StudentDetails.studentdetails')),
                ('SUB1', models.IntegerField()),
                ('SUB2', models.IntegerField()),
                ('SUB3', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
