# Generated by Django 4.2.4 on 2023-08-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDetails', '0002_studentmarks_alter_studentdetails_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
